"""update tables

Revision ID: 2c0cc6d8c636
Revises: 21810134bcfd
Create Date: 2026-02-21 20:38:32.405150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0cc6d8c636'
down_revision: Union[str, Sequence[str], None] = '21810134bcfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'applications', ['status'])
    op.create_unique_constraint(None, 'cities', ['name'])
    op.create_unique_constraint(None, 'employment_types', ['name'])
    op.drop_constraint(op.f('employment_types_vacancy_id_fkey'), 'employment_types', type_='foreignkey')
    op.drop_column('employment_types', 'vacancy_id')
    op.create_unique_constraint(None, 'professions', ['name'])
    op.create_unique_constraint(None, 'roles', ['name'])
    op.add_column('vacancies', sa.Column('employment_type_id', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('work_schedule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'employment_types', ['employment_type_id'], ['id'])
    op.create_foreign_key(None, 'vacancies', 'work_schedules', ['work_schedule_id'], ['id'])
    op.create_unique_constraint(None, 'work_schedules', ['name'])
    op.drop_constraint(op.f('work_schedules_vacancy_id_fkey'), 'work_schedules', type_='foreignkey')
    op.drop_column('work_schedules', 'vacancy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_schedules', sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('work_schedules_vacancy_id_fkey'), 'work_schedules', 'vacancies', ['vacancy_id'], ['id'])
    op.drop_constraint(None, 'work_schedules', type_='unique')
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'work_schedule_id')
    op.drop_column('vacancies', 'employment_type_id')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'professions', type_='unique')
    op.add_column('employment_types', sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('employment_types_vacancy_id_fkey'), 'employment_types', 'vacancies', ['vacancy_id'], ['id'])
    op.drop_constraint(None, 'employment_types', type_='unique')
    op.drop_constraint(None, 'cities', type_='unique')
    op.drop_constraint(None, 'applications', type_='unique')
    # ### end Alembic commands ###
