"""rebild db

Revision ID: 3b4e21d7c6c1
Revises: d51ee614121a
Create Date: 2026-03-03 22:23:08.288518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4e21d7c6c1'
down_revision: Union[str, Sequence[str], None] = 'd51ee614121a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_role_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_role_id_key'), 'users', ['role_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
